name: luthemes

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: composer install
      - name: step three
        run: npm install
      - name: step four
        run: npm run build
      - name: step five
        run: sed -i -e "s/luthemes.test/luthemes.com/g" "luthemes/app/functions-config.php"
      - name: step six
        run: rsync -r luthemes/* ~/public_html
      - name: step seven
        run: rm -rf ~/public_html/user/cache