name: luthemes

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: npm run build
      - name: step three
        run: rm -rf ~/public_html/wp-content/themes/luthemes
      - name: step four
        run: mv -f luthemes ~/public_html/wp-content/themes/luthemes