name: luthemes

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
         run: composer install
      - name: step three
         run: npm run build